### ISSUE TITLE
Admin General Settings & Project Info: Email address isn't matched including the user email.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Burgess-Design-Group#1]
![image](https://cloud.githubusercontent.com/assets/13363508/16370683/4a1d5640-3c74-11e6-9bad-71dc0b788fab.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16370691/68e8210e-3c74-11e6-9a34-d19ac4f0ff55.png)

**Comment by jsemblantetitanweb** [comment]
Incorrect project info email used.
