### ISSUE TITLE
Admin - Our Project Category & BDG International Category : Incorrect default image used. Just leave the field empty if there were no image uploaded.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Burgess-Design-Group#100]
![7](https://cloud.githubusercontent.com/assets/18256652/16479870/9eedb184-3ed5-11e6-8e76-6289672197cb.png)

**Comment by jsemblantetitanweb** [comment]
This is not a bug. This is the default image use by the plugin if it has no image use or the image section is blank. It is like a image placeholder.

**Comment by iteano** [comment]
How about just changing this with the no default image use for this site. To be formal and presentable.
