### ISSUE TITLE
General Inner Sidebar: "Today" goes over the next line, from the Form "Contact Us Today" Heading.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Burgess-Design-Group#48]
![image](https://cloud.githubusercontent.com/assets/13363508/16403187/36842030-3d25-11e6-9d89-e7ca066e4fe6.png)

**Comment by maehtitan** [comment]
not yet fixed in Firefox and IE browsers

**Comment by jsemblantetitanweb** [comment]
Fix font size adjusted.
