### ISSUE TITLE
Services: Incorrect font-size used in unordered list and ordered list.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Burgess-Design-Group#73]
![image](https://cloud.githubusercontent.com/assets/13363508/16476285/7791cda4-3eb8-11e6-94e6-c5fcc0210f26.png)

**Comment by jsemblantetitanweb** [comment]
I have rechecked it again and it seems like it is already being fix. Screenshot below

![image](https://cloud.githubusercontent.com/assets/18159491/16825594/9b813ea2-49a8-11e6-9eb5-cc7a2c78f9e9.png)
