### ISSUE TITLE
Our Projects - Category : Incorrect numerical ordered list of the content.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Burgess-Design-Group#80]
![1](https://cloud.githubusercontent.com/assets/18256652/16478040/8d129cc4-3ec9-11e6-8362-03398af66274.png)

**Comment by iteano** [comment]
Still observed on single pages.
![image](https://cloud.githubusercontent.com/assets/18256652/16795261/e9d515e6-490e-11e6-9150-31de8f59fa95.png)

**Comment by jsemblantetitanweb** [comment]
I have checked the backend and it seems like it is being inputted separately that makes the issue visible. They are being inputted in (2) separate ordered list. Thanks.
